development:
  adapter: sqlite3
  database: tmp/db/development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: tmp/db/test.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: tmp/db/production.sqlite3
  timeout: 5000
